---
title: List
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  new-4002:
    title: new-4002
    output: true
    permalink: new-1002-perm
